# Generated by Django 3.0 on 2023-05-23 15:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=100, unique=True)),
                ('stock_image', models.CharField(max_length=500, null=True)),
                ('stock_delta', models.FloatField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stocks', djongo.models.fields.JSONField()),
            ],
        ),
    ]
