# Generated by Django 3.0 on 2023-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stock_stock_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_delta',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_diff',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
